### ISSUE TITLE
[Bug] After the build, we are getting argon-dashboard-react/static/js/main.e8eb0f76.chunk.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by vengatbap** [creativetimofficial/argon-dashboard-react#18]
### Version
* Argon Dashboard React - v1.0.0
### Reproduction link
https://www.creative-tim.com/new-issue/argon-dashboard-react
### Operating System
masos
### Device
Apple
### Browser & Version
Chrome 64
### Steps to reproduce
After the build, we are getting argon-dashboard-react/static/js/main.e8eb0f76.chunk.js net::ERR_ABORTED 404 (Not Found)
### What is expected?
url need to come like this /static/js/main.e8eb0f76.chunk.js
### What is actually happening?
but it come like this argon-dashboard-react/static/js/main.e8eb0f76.chunk.js

---

**Comment by einazare** [comment]
Hello there, @vengatbap ,

Thank you for your interest in working with our products.
The link you have provided for the reproduction seems to be wrong, it redirects me to the new-issue template of our platform. Was this intentional? If you did not know what link to give us, next time please create the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run `node -v`
* Run `npm -v`
* [MAC/Ubuntu/Linux] Run npm run install:clean
* [Windows] Run `npm install`
* [Windows] Run `npm start`
* Showcase the issue

And add a link to that video.

To solve the issue, please delete the homepage prop from the package.json file and run again the build command (also, before that delete the old build).

Best,
Manu
