### ISSUE TITLE
Unable to make table scrollable. With fixed header

### ISSUE THREAD

**Issue by Robokishan** [creativetimofficial/argon-dashboard-react#31]
### Version
Latest
### Reproduction link
https://github.com/creativetimofficial/argon-dashboard-react
### Operating System
Mac
### Device
Mac
### Browser & Version
Chrome latest
### Steps to reproduce
1. Just using github repo
2. Added couple of more lines to table example
3. Trying to make table scrollable with fixed header bar when scrolling vertical and also fixed first column when horizontal scrolling.
### What is expected?
Vertical Scrolling with fixed header.
Horizontal scrolling with  fixed first column
### What is actually happening?
Header is scrolling with all rows.

---
### Solution
I don't know. I am planning to purchase but saw this bug in free version.so i am stuck.

**Comment by einazare** [comment]
Hello there, @Robokishan ,

I really do not see how this is an issue with our product, we do not offer that functionality.
Please provide me with an actual reproduction link, the link you have given us, sends me to this repository.
Please provide me with some better steps, the 3rd steps tells me `to try to make...`, I really believe this step should be something like
4. Go inside X
5. Add class Y on
6. Add the following CSS
7. ETC.

I need a step by step guide on how to reproduce your issue, but once again, I don't think this issue is caused by our product.

Best,
Manu
