### ISSUE TITLE
[Bug] Build success without any error, but app blank.

### ISSUE THREAD

**Issue by difaananda40** [creativetimofficial/argon-dashboard-react#6]
### Version
1.0.0
### Reproduction link
https://imgur.com/X7k7KUc
### Steps to reproduce
1. Run npm build
2. Build success without any error.
3. Running build using serve -s build
4. Open the apps, then the app show nothing.
5. Theres error in console log.
### What is expected?
App running.
### What is actually happening?
App show nothing

---

**Comment by einazare** [comment]
Hello there, @difaananda40 ,

As I've already told you on your last 2 issues, this issue was already addressed here: https://github.com/creativetimofficial/argon-dashboard-react/issues/3
You just need to read through the comments, and the solution is there.
I will give you here the solution as well, but next time, if you open a duplicate issue, I will ignore it completely. It is quite hard to give the same response over and over again (my manager does not agree with giving the same response over and over again, and I might have issues by doing so), hope you can understand my situation.
> Hello there, @Thomas-Smyth @Leo1212 ,
> 
> Thank you for your interest in working with our products.
> Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday:
> 
> * https://www.calendar-12.com/holidays/easter
> * https://www.officeholidays.com/religious/orthodox/orthodox_easter.php
> 
> Please go inside `src/assets/scss/custom/_icons.scss` and delete the following lines:
> 
> * `width: calc(100% - $icon-size-sm - 1);`
> * `width: calc(100% - $icon-size-lg - 1);`
> * `width: calc(100% - $icon-size-xl - 1);`
> * `width: calc(100% - #{$icon-size} - 1);`
> 
> Also, for deploying you will have to delete the homepage prop from the package.json file.
> 
> All the best,
> Manu
> ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)
> 
> Trying to help the open source community:
> 
> * https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
> * https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
> * https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f
> * https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
> * https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
> * https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
> 
> If you've liked what you saw, help me with a comment, like, share or subscribe.

Here is a link to that response: https://github.com/creativetimofficial/argon-dashboard-react/issues/3#issuecomment-489524888

Best,
Manu
