### ISSUE TITLE
[Feature Request] How to route to individuals elements by id

### ISSUE THREAD

**Issue by jgomesj** [creativetimofficial/argon-dashboard-react#8]
### What is your enhancement?
hi, I'm try to use this template, but I don't know how to route to specif urls. for example, we have a lot of users and I whant to navigate to the profile of the user by id in the url some like this localhost:3000/admin/user/23345345.

how can I do this?

thanks

**Comment by einazare** [comment]
Hello there, @jgomesj ,

Thank you for your interest in working with our products.
Your question is not really an enhancement to our product, it is more a question for StackOverflow.
To be honest I haven't worked with params inside links in React.
But I am pretty sure that if you add inside our routes something like:
```
...
route: "user/:id",
layout: "admin"
...
```
It should work just fine.
The only thing that you will have to do, is set that ID as well in the sidebar component, and also change what the User page renders based on that ID - but once again, since I haven't done this, I do not know what guidance to give you, other than try to find the solution on StackOverflow/Google. Or maybe, someone will see your issue and come to your help.

Best,
Manu
